name: Build and Deploy Activity Tracking to AWS ECR

on:
  push:
    branches:
      - main
      # Temporarily running this pipeline for this branch
      - activity-tracking-tests
    paths:
      - "activity-tracking/**"
  pull_request:
    branches:
      - main
    paths:
      - "activity-tracking/**"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: cfgmla23
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name mongo_container
        ports:
          - 27017:27017   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Setting up CI pipeline to run npm tests
      - name: Run npm test
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          cd activity-tracking
          npm ci
          npm run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR (Activity Tracking)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mla-fitnessapp-activity
          IMAGE_TAG: latest
        run: |
          cd activity-tracking
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG